name: Deploy to Aliyun ECS via SSH

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.134.2"
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Copy files via rsync
        run: |
          rsync -avz --delete public/ root@bd8dhf.com:/var/www/rool.me/
          ssh root@bd8dhf.com 'chown -R www-data:www-data /var/www/rool.me/'
          ssh root@bd8dhf.com 'systemctl restart nginx'
